<?php

namespace App\Tests\Sync;

use CeculaSyncApiClient\SyncSms;
use PHPUnit\Framework\TestCase;

class SyncSmsTest extends TestCase
{
    private SyncSms $syncSms;

    public function setUp(): void
    {
//        parent::setUp(); // TODO: Change the autogenerated stub
        $this->syncSms = new SyncSms();
    }

    /**
     * @test
     * @throws \Exception
     */
    public function sendSmsThrowsExceptionWhenRecipientsIsNotProvided(): void
    {
        self::expectException(\Exception::class);
        self::expectExceptionCode(404);
        $this->syncSms->sendSMS("hello", []);
    }


    /**
     * @param array $numbers
     * @test
     * @dataProvider supplyNumbers
     * @throws \Exception
     */
    public function sendSmsThrowsExceptionWhenNumberIsInvalid(array $numbers): void
    {
        self::expectException(\Exception::class);
        self::expectExceptionCode(100);
        $this->syncSms->sendSMS("hello", $numbers);
    }


    public function supplyNumbers(): array
    {
        return [
            [["234818317277012"],["234818317277013"]],
            [["23481831727701"],["hello"]]
        ];
    }
}
